export const HOME = '/'
export const BLOGS = '/blogs'
export const BLOG_DETAILS = '/details/'
export const ABOUT = '/about'
export const CONTACT = '/contact'
export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const SEND_VERIFICATION = '/sendVerification'
