import { Box } from '@chakra-ui/react'
import BlogCard from '@components/Common/BlogCard'
import MainLayout from '@components/Common/MainLayout'
import RecentPosts from '@components/HomePage/RecentPosts'
import Head from 'next/head'
import { getBlogs } from '../services/blog'

const featuredPost = {
  id: 1,
  title: 'Is React better than Vue for your project?',
  content:
    'This is a description of the topic which is really good going. lorem ipsum is a dummy text which is used to fill the space of the content.',
  createdat: '2021-10-10',
  coverimage: '/images/image1.webp',
  category: 1,
  categoryname: 'React',
  published: true
}

export default function Home({ blogs }: { blogs: IBlog[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Box>
          <BlogCard card={featuredPost} imagHeight={300} />
          <RecentPosts blogs={blogs} />
        </Box>
      </MainLayout>
    </>
  )
}

export async function getServerSideProps() {
  try {
    const blogs = await getBlogs()

    if (blogs) {
      return {
        props: {
          blogs: blogs
        }
      }
    } else {
      return {
        props: {
          blogs: []
        }
      }
    }
  } catch (error) {
    return {
      props: {
        blogs: []
      }
    }
  }
}
